
const motivationalQuotes = [
  "Keep pushing forward.",
  "Progress, not perfection.",
  "You are your only limit.",
  "Don’t wish for it. Work for it.",
  "One step at a time.",
  "Small progress is still progress.",
  "Discipline over motivation.",
  "Sweat now, shine later.",
  "Make yourself proud.",
  "You got this.",
  "Your body hears everything your mind says.",
  "Be stronger than your excuses.",
  "Focus on the goal.",
  "Push yourself, no one else will.",
  "Fall seven times, get up eight.",
  "Consistency is key.",
  "Train insane or remain the same.",
  "No pain, no gain.",
  "Work hard in silence.",
  "Keep grinding.",
  "Every rep counts.",
  "Progress takes patience.",
  "Your future self will thank you.",
  "The only bad workout is the one you didn’t do.",
  "It’s not supposed to be easy.",
  "Winners train, losers complain.",
  "Never stop improving.",
  "Earn your results.",
  "Be better than yesterday.",
  "Pain is temporary. Pride is forever."
];
